image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaSnmConverter" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore XwaSnmConverter\XwaSnmConverter.sln

build:
  project: XwaSnmConverter\XwaSnmConverter.sln
  verbosity: minimal

after_build:
- XwaSnmConverter\build-dist.cmd

artifacts:
- path: XwaSnmConverter\dist
  name: XwaSnmConverter-$(APPVEYOR_BUILD_VERSION)
  type: zip
